### ISSUE TITLE
no response when right clicking--> combine files

### ISSUE THREAD

**Issue by dticson** [BateleurIO/vscode-combine-files#3]
I am on the latest vs code (I think march version that just updated recently), and when I select multiple files, then right click and select combine, nothing happens.  Worked in prior versions.

**Comment by CobusKruger** [comment]
Thank you for reporting this. It's a bug I introduced while merging from the Azure Data Studio version. I fixed and synced it a few minutes ago. The new version is already published, so I'll close this.
