### ISSUE TITLE
creating multiple files

### ISSUE THREAD

**Issue by dticson** [BateleurIO/vscode-combine-files#5]
I tried to use it today, and it's creating multiple files, some with comments that are not commented out properly.

**Comment by CobusKruger** [comment]
Hi, thanks for getting in touch.

Could you share the input files, or files that produce this problem?

**Comment by dticson** [comment]
![image](https://user-images.githubusercontent.com/38885240/56428322-f19c3300-628c-11e9-9c83-a9a63da09e20.png)

Any two files really - attached are the ones for this example.  Also a screenshot.

[Functions.zip](https://github.com/BateleurIO/vscode-combine-files/files/3098370/Functions.zip)

**Comment by CobusKruger** [comment]
Thank you for this.

There was a problem in an upstream repository. I updated the dependency and republished the extension. It's already live.
