### ISSUE TITLE
Option to have temp file created in the project/folder/workspace root

### ISSUE THREAD

**Issue by macintacos** [BateleurIO/vscode-combine-files#8]
This is more of a question than anything, but is it possible to do one of the following:

- Have Combine Files create the temporary file in the top-level directory in the project/folder/workspace you're looking at?
- Make Combine Files "know" if all of the files are in the same directory, and then make the tempfile in the same directory?
- Make Combine Files "know" where we are in a project/folder, and pick the "next-highest" directory for where the tempfile should go? So for example:

	```
	- Folder 1
		- Sub-directory
			- Combineme.md
			- Sub-directory
				- Combinemetoo.md
	```
	Would become:
	```
	- Folder 1
		- temp-combineme-and-combinemetoo.md
		- Sub-directory
			- Combineme.md
			- Sub-directory
				- Combinemetoo.md
	```

	So that temp files could be intelligently placed?

I haven't looked into the extension thoroughly but none of these were immediately apparent from the configuration settings that I saw.

**Comment by CobusKruger** [comment]
Hi and thanks for reaching out.

I like the idea of dynamically figuring out where to place the file and I think both of the first two options could be simple enough to do. Number three makes it more complex and may make it difficult for the user to figure out where the file has gone.

I think there are a couple of questions worth exploring though, so I would appreciate it if you could share your thoughts on these points:

1. There is a configuration option for `outputFileName`, which does what it says on the tin. your suggestions could make a config file unnecessary in many cases (and I like that), but what other benefits do you see?
2. My primary concern would be determining the file name to use. Right now it is generated in a temp folder, so it doesn't really matter if running the extension several times generates different file names. In the project tree itself, you don't want a bunch of files with randomized names accumulating over time. The obvious choice seems to be to name the file according to the folder, accounting for name collisions. To me, `outputFileName` was a simple way to make it unambiguous, but that makes a config file mandatory.
