### ISSUE TITLE
HELP Either extension's buggy with VS Code new version 1.38.1 or I'm failing configuration

### ISSUE THREAD

**Issue by JCarlosGarza** [BateleurIO/vscode-combine-files#9]
I can't combine files selecting root folder with SQL scripts. I add a configuration file with parameters given and I tried editing from workspace settings too. Do you have screenshots or a video of where the temporary output file is created?

**Comment by CobusKruger** [comment]
Hi there. A video is a cool idea, but I don't have one to share right now. Sorry.

If you are creating custom a configuration file and a file is not created, please share the config file with me so I can try to recreate the exact issue.

The default configuration is pretty complete though, and here is a step-by-step guide on how I would use that. I don't know what your folder structure looks like, so for this guide, assume it looks like this:

```
-- Project
  +-- SQL
     +-- file1.sql
     +-- file2.sql
```

1. Open the `Project` folder in VS Code.
2. Open the Explorer view (the tree view on the left showing the files in your workspace).
3. Right-click the `SQL` folder and choose _Combine Files_.

And that's it. A new file should open in the editor, containing the combined content of the files in that folder. The file will be in your temp folder and you'll need to save it under the preferred name.

Having a configuration file in your workspace allows you to specify a preferred file name (which can then be outside the temp folder) and also to override default headings, footers and dividers within the workspace.
